spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prices
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      default_schema: prices
      ddl-auto: create
  sql:
    init:
      mode: always


