spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prices
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
    enabled: true
flyway:
  url: jdbc:postgresql://localhost:5432/prices
  user: root
  password: root
  schemas: prices


